### ISSUE TITLE
ALT+TAB blur not triggered

### ISSUE THREAD

**Issue by whallz** [serkanyersen/ifvisible.js#18]
tested on Chrome 40.0.2214.115 m on Windows 8.1, no blur event trigger after switching to another program/window with ALT+TAB.

**Comment by dasilvacontin** [comment]
Someone please confirm this.

**Comment by serkanyersen** [comment]
triggering the blur or focus event totally depending on the browser. Since ifvisible.js is a wrapper around Visibility API, I have no control over how these events are triggered.

However, if the application still visible in the background, blue event will not be triggered. That's how visibility API works.
